### ISSUE TITLE
Finalize Hackerlounge crew

### ISSUE THREAD

**Issue by flaki** [MozillaHU/hackerlounge#5]
Gather final crew for the Hackerlounge days for "booth" & conference support.

Hackerlounge days:

|  | Wednesday | Thursday | Friday |
| :-- | :-: | :-: | :-: |
|  | May 11 | May 12 | May 13 |
|  | CSSConf | JSConf Day 1 | JSConf Day 2 |
| 6:00 | Preparation | - | - |
| 8:00 | Set up | Set up | Set up |
| 10:00 |  | Open Session | Open Session |
| 11:00 | Open Session |  |  |
| 12:00 | Lunch | Lunch | Lunch |
| 13:00 | Session | Session | Session |
| 15:00 |  | Session | Session |
| 17:00 |  | Session | Wrapping up |
| 18:00 |  | Closing | - |

Please comment on availability. In the case of JSConf we will be giving preference to those who can make both days. One could apply for all 3 days but we will be assigning tickets to achieve maximum participation and with diversity in mind.

Please comment like:

> "CSSConf" or "Wednesday/Szerda": **prefer/maybe**
> "JSConf day 1" or "Thursday/Csütörtök": **prefer/maybe**
> "JSConf day 2" or "Friday/Péntek": **prefer/maybe**

Mark the days with "prefer" if you'd prefer to attend said date, mark any non-preferential dates with "maybe" if you can attend. For dates you cannot make, just leave out the entire row.

**Comment by flaki** [comment]
> Wednesday/Szerda: **prefer**
> Thursday/Csütörtök: **prefer**
> Friday/Péntek: **prefer**

_Note: Hackerlounge Host_

**Comment by Dlimk** [comment]
_Wednesday/Szerda:_ **prefer**
_Thursday/Csütörtök:_ **prefer**
_Friday/Péntek:_ **prefer**

**Comment by samtelen** [comment]
""Wednesday/Szerda": prefer
"Thursday/Csütörtök": prefer
"Friday/Péntek": prefer

**Comment by gabrielmicko** [comment]
Wednesday/Szerda: for your service, Sir
Thursday/Csütörtök: for your service, Sir
Friday/Péntek: for your service, Sir

**Comment by rangeoshun** [comment]
_Wednesday/Szerda:_**maybe**
_Thursday/Csütörtök:_**prefer**
_Friday/Péntek:_**prefer**

**Comment by kviktorman** [comment]
Wednesday/Szerda:perfer
Thursday/Csütörtök:prefer
Friday/Péntek:prefer

**Comment by meskobalazs** [comment]
Thursday/Csütörtök: **prefer**
Friday/Péntek: **prefer**

**Comment by flaki** [comment]
Final crew: @meskobalazs, @samtelen, @kviktorman + @rangeoshun (only Thu/Fri), with @Dlimk & @gabrielmicko as co-organizers.

**Comment by MaoHUN** [comment]
Thursday/Csütörtök:prefer
Friday/Péntek:prefer
